### PR TITLE
feat: add tsconfig file config option

### PR DESCRIPTION
**Pull request by rek**
This allows the user to add a custom tsconfig file path.

Useful when nest makes `tsconfig.app.json` files.

### CODE REVIEW

**Comment by rek** [comment]
cc @clement-estone

**Comment by rek** [comment]
@Godefroy are you able to help review this? Would love to get this option in, it would help with my usage of this lib a lot! :)

**Comment by clement-estone** [comment]
Sorry I was away for a few weeks.
This LGTM, merging.
Thanks for your contribution ;)

**Comment by rek** [comment]
Awesome. Thanks :)

What do you think about this one too: https://github.com/lonestone/nest-sdk-generator/pull/6/files ?

**Pull request merged**
